#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 26 17:02:57 2019

@author: dieinimy
"""
0.7559 - Base line classifier (ZeroR)

0.4767 - Naive Bayes (labelencoder + onehotenconder + escalonamento)
0.7952 - Naive Bayes (labelencoder)
0.7950 - Naive Bayes (labelencoder + onehotencoder)
0.8057 - Naive Bayes (labelencoder + escalonamento)


0.8102 - Árvore de decisão (labelencoder + onehotencoder + escalonamento)
0.8128 - Árvore de decisão (labelencoder)
0.8102 - Árvore de decisão (labelencoder + onehotencoder)
0.8128 - Árvore de decisão (labelencoder + escalonamento)

0.8476 - Random forest n_estimators = 40 (labelencoder + onehotencoder + escalonamento)
0.8471 - Random forest n_estimators = 40 (labelencoder)
0.8489 - Random forest (labelencoder + onehotencoder)
0.8483 - Random forest (labelencoder + escalonamento)

0.7880 - CN2 (sem pré-processamento)

0.8223 - KNN 5 (labelencoder + onehotenconder + escalonamento),
0.7746 - KNN 5 (labelencoder)
0.7760 - KNN 5 (labelencoder + onehotencoder)
0.8219 - KNN 5 (Naive Bayes (labelencoder + escalonamento)

0.8495 - Regressão logistica (labelencoder + onehotenconder + escalonamento)
0.7909 - Regressão logistica (labelencoder)
0.7954 - Regressão logistica (labelencoder + onehotencoder)
0.8184 - Regressão logistica (Naive Bayes (labelencoder + escalonamento)

0.8507 - SVM 'linear' (labelencoder + onehotenconder + escalonamento)
0.8491 - SVM 'rbf' (labelencoder + onehotenconder + escalonamento)
? - SVM linear (labelencoder)
? - SVM linear labelencoder + onehotencoder)
0.8507 - SVM linear (Naive Bayes (labelencoder + escalonamento)