#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 26 14:13:50 2019

@author: dieinimy
"""

Credit Data
-----------

0.9379 - Naive Bayes (inconsistentes + faltantes + escalonamento)
0.9819 - Árvore de decisão (inconsistentes + faltantes + escalonamento)