#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 26 14:13:50 2019

@author: dieinimy
"""

Credit Data
-----------
0.8720 - Base line classifier
0.9379 - Naive Bayes (inconsistentes + faltantes + escalonamento)
0.9819 - Árvore de decisão (inconsistentes + faltantes + escalonamento)
0.9839 - Random forest n_estimatores = 40 (inconsistente + faltante + escalonamento)
0.9520 - CN2 (sem pré-processamento)
0.9859 - KNN (inconsistente + faltante + escalonamento)